mensagens = [
    "Acredite em si mesmo e tudo será possível.",
    "O sucesso é a soma de pequenos esforços repetidos diariamente.",
    "Grandes conquistas começam com pequenos passos.",
    "O fracasso é apenas uma oportunidade para recomeçar com mais experiência.",
    "A persistência é o caminho do êxito.",
    "Não deixe o medo impedir você de tentar.",
    "Você é mais forte do que imagina.",
    "O melhor momento para começar foi ontem. O segundo melhor momento é agora.",
    "Os desafios são oportunidades disfarçadas.",
    "A jornada é tão importante quanto o destino.",
    "Cada novo dia é uma nova chance de fazer melhor.",
    "Nada pode impedir alguém com determinação.",
    "O sucesso é construído na disciplina diária.",
    "Aprenda com os erros e siga em frente.",
    "Nunca é tarde para ser quem você quer ser.",
    "O esforço de hoje é a vitória de amanhã.",
    "Acredite nos seus sonhos e lute por eles.",
    "Seja a mudança que você quer ver no mundo.",
    "O progresso é mais importante do que a perfeição.",
    "Você pode ser tudo o que quiser, basta trabalhar para isso.",
    "Se você pode sonhar, pode realizar.",
    "Não importa o quão devagar você vá, desde que não pare.",
    "Acredite no processo e confie na jornada.",
    "O impossível é apenas uma opinião.",
    "Seja persistente e os resultados virão.",
    "A motivação leva ao início, mas a disciplina mantém o progresso.",
    "Erga a cabeça e siga adiante, dias melhores virão.",
    "O seu esforço de hoje definirá o seu amanhã.",
    "Nada é impossível para quem acredita.",
    "O segredo do sucesso é nunca desistir.",
    "Ação gera motivação, então comece agora!",
    "Sua atitude determina sua altitude.",
    "Você é capaz de coisas incríveis!",
    "Cada obstáculo superado é uma vitória conquistada.",
    "Confie no seu potencial.",
    "Nunca subestime o poder da sua força interior.",
    "O medo só existe na sua cabeça, supere-o.",
    "Sucesso é a recompensa da perseverança.",
    "Conquistas vêm para aqueles que se esforçam.",
    "Não deixe a dúvida matar os seus sonhos.",
    "O que você faz hoje determina seu futuro.",
    "Nada cresce na zona de conforto.",
    "Não espere por oportunidades, crie-as.",
    "Dê um passo de cada vez, mas continue avançando.",
    "Você já venceu muitas batalhas, não pare agora.",
    "Desafios são apenas degraus para o sucesso.",
    "Seja a sua própria inspiração.",
    "Grandes sonhos exigem grandes esforços.",
    "Se não desafiar você, não fará você crescer.",
    "Seja persistente como a água moldando uma rocha.",
    "Tudo começa na sua mente, então pense positivo!",
    "Nunca desista daquilo que faz seu coração vibrar.",
    "O tempo passa de qualquer forma, use-o a seu favor.",
    "Quanto maior o desafio, maior a vitória.",
    "Você tem dentro de si tudo o que precisa.",
    "Erros são apenas lições disfarçadas.",
    "Nada pode deter um coração determinado.",
    "Você tem potencial para ir muito além!",
    "O único limite é aquele que você impõe a si mesmo.",
    "Sucesso é resultado de esforço contínuo.",
    "Foque no progresso, não na perfeição.",
    "As dificuldades preparam pessoas comuns para destinos extraordinários.",
    "O medo é um mentiroso, não acredite nele.",
    "Você é capaz de superar qualquer desafio.",
    "Nunca subestime o seu próprio poder.",
    "Cada esforço conta, mesmo que pareça pequeno.",
    "O primeiro passo é sempre o mais difícil, mas vale a pena.",
    "Você nasceu para vencer.",
    "Seja resiliente, tudo se encaixa no tempo certo.",
    "Seu potencial é ilimitado.",
    "Nada pode parar quem tem um objetivo claro.",
    "Seja disciplinado e os resultados aparecerão.",
    "A cada dia, você está mais perto do seu objetivo.",
    "O esforço de hoje é a recompensa de amanhã.",
    "O sucesso vem para quem se atreve a ir além.",
    "Você pode transformar qualquer desafio em uma oportunidade.",
    "Mantenha-se firme, sua vitória está a caminho.",
    "O único fracasso real é parar de tentar.",
    "Você é mais corajoso do que pensa.",
    "O seu futuro depende do que você faz no presente.",
    "Acredite no seu talento e siga em frente.",
    "Toda grande jornada começa com um único passo.",
    "Não existe sucesso sem esforço.",
    "Você é o criador do seu próprio destino.",
    "Seu esforço e dedicação valerão a pena.",
    "Você pode mudar sua história a qualquer momento.",
    "O medo não pode controlar você.",
    "Cada obstáculo vencido é um degrau a mais na sua escalada.",
    "O sucesso vem para aqueles que nunca desistem.",
    "Seus sonhos valem o seu esforço.",
    "Continue em frente, você está mais perto do que imagina.",
    "O caminho do sucesso é pavimentado com persistência.",
    "A vida recompensa aqueles que não desistem.",
    "Grandes feitos exigem coragem e persistência.",
    "Seu crescimento começa quando você sai da sua zona de conforto.",
    "Cada dia é uma nova oportunidade para evoluir.",
    "Acredite no impossível e o torne possível.",
    "Nada pode parar quem tem determinação e fé.",
    "Você está no controle do seu próprio destino.",
]